# Generated by Django 2.2.12 on 2022-05-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_user',
            name='pawrd',
            field=models.CharField(max_length=255),
        ),
    ]
